language: python

install:
  - pip install .
  - pip install -r requirements.txt

script:
  - ./test.sh
  
notifications:
  email:
    on_success: never # default: change
    on_failure: never # default: always
    on_change: always
